services:
  esp-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env.docker
    environment:
      - APPLICATION_PORT=3000
    ports:
      - "${ESP_API_PORT:-3003}:3000"
